
[manager]
layout         = [ 1, 4, 3 ]
show_hidden    = false
show_symlink   = true
sort_by        = "natural"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true

[preview]
tab_size        = 2
max_width       = 600
max_height      = 900
cache_dir       = ""
image_filter    = "triangle"
image_quality   = 75
sixel_fraction  = 15
ueberzug_scale = 1

[opener]
folders = [
    { run = 'open -R "$@"', desc = "Reveal in Finder" },
]
